In [12]:
import numpy as np

In [9]:
a = np.arange(10).reshape(2,5)

In [13]:
a = np.arange(10).reshape(2,5)

In [14]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
a.shape

(2, 5)

Return the dimension of the array

In [16]:
a.ndim

2

In [17]:
a.dtype

dtype('int32')

In [18]:
a.dtype.name

'int32'

In [19]:
a.itemsize

4

In [20]:
a.size

10

Creating a complex array

In [23]:
c = np.array([[1, 2], [3, 4]], dtype='complex')

In [24]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Create nxn array of all zeros

In [26]:
z = np.zeros([2,2])

In [27]:
z

array([[ 0.,  0.],
       [ 0.,  0.]])

Create nxn array of all ones

In [28]:
one = np.ones([2,2,3])

In [29]:
one

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

'ones_like()' will create an array of same size and type but value with al ones. Similarly, zeros_like, empty_like

In [37]:
np.ones_like(z)

array([[ 1.,  1.],
       [ 1.,  1.]])

In [30]:
emp = np.empty([2,3]) # Empty array

In [31]:
emp

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Like 'range()' numpy also have its function for sequence of numbers

In [32]:
r = np.arange(1, 10, 2) # Increment by 2

In [33]:
r

array([1, 3, 5, 7, 9])

In [34]:
np.arange(0.2, 2.0, 0.2)

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])

Due to limit in floaing point precision 'arange()' doesn't work well with floating number as arguments since we can't predict the number of outcomes so 'linspace()' is used who takes 3 argument
1. starting number
2. halt or stop at
3. total number of elements to be return
This number return are equally space with each other.

In [35]:
np.linspace(1, 10, 20)

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

Arithmetic Operations on array are element wise

In [42]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
b = np.arange(4)
print(b)

[0 1 2 3]


In [46]:
c = a + b
print(c)

[1 3 5 7]


In [47]:
c = a - b
print(c)

[1 1 1 1]


In [45]:
c = a * b
print(c)

[ 0  2  6 12]


In [48]:
c = a / b
print(c)

[        inf  2.          1.5         1.33333333]


C:\Users\OWNER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [49]:
b[0] = 4
print(b)

[4 1 2 3]


In [50]:
c = a / b
print(c)

[ 0.25        2.          1.5         1.33333333]


In [51]:
b ** 2     # Exponent (Square)

array([16,  1,  4,  9])

In [52]:
print(b)
print(b < 3)

[4 1 2 3]
[False  True  True False]


As seen above, a * b perform element wise product if you want matrix product then 'dot()' is used.

In [101]:
a = np.arange(4).reshape(2,2)
b = np.array([[1,2], [1,2]])
print('A\n', a)
print('B\n', b)
c = np.dot(a,b)
print('C(dot product)\n',c)

A
 [[0 1]
 [2 3]]
B
 [[1 2]
 [1 2]]
C(dot product)
 [[ 1  2]
 [ 5 10]]


Python also shorthand operators such as +=, *=, -=, /= that means perform the operation on the same variable

In [67]:
print(a)
a += 2
print(a)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [68]:
print(a)
a -= 2
print(a)

[[3 4]
 [5 6]]
[[1 2]
 [3 4]]


On working with array of different data types, the resulted array type is of the more general or precise i.e. upcasting

In [72]:
a = np.array([ [1,2], [1,2]], dtype='int32')
b = np.linspace(2,3, 4).reshape(2,2)

In [76]:
b.dtype

dtype('float64')

In [77]:
c = a + b
print(c)
print(b.dtype)

[[ 3.          4.33333333]
 [ 3.66666667  5.        ]]
float64


numpy also provide some unary operations functions such as max, min, sum, mean, std, etc.

In [86]:
a = np.arange(10)
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())

[0 1 2 3 4 5 6 7 8 9]
9
0
45
4.5
2.87228132327


Operation can also be performed on particular row or column by passing the 'axis' argument, 
'0' for row
'1' for column

In [96]:
a = np.arange(9).reshape(3, 3)
print('A:\n',a)
print('Row-wise sum:\n',a.sum(axis=0))
print('Column-wise sum:\n',a.sum(axis=1))
print('Max element row-wise:\n',a.max(axis=0))
print('Cumulative sum row-wise \n', a.cumsum(axis=0))

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Row-wise sum:
 [ 9 12 15]
Column-wise sum:
 [ 3 12 21]
Max element row-wise:
 [6 7 8]
Cumulative sum row-wise 
 [[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


Numpy also have some special universal mathematical functions such as add, subtract, exp, round, sqrt, cov, etc.

In [123]:
x = np.array([[1,2], [3,4]])
y = np.array([[4,5],[6,7]])
print(x)
print('\nAdd\n',np.add(x,y))
print('\nSubtract\n',np.subtract(x,y))
print('\nSquare root\n',np.sqrt(x))
print('\nExponent\n',np.exp(x))
print('\nCovariance\n',np.cov(x))
print('\nMaximumm\n',np.max(x))
print('\nMedian\n',np.median(x))
print('\nTranspose\n',np.transpose(x))

[[1 2]
 [3 4]]

Add
 [[ 5  7]
 [ 9 11]]

Subtract
 [[-3 -3]
 [-3 -3]]

Square root
 [[ 1.          1.41421356]
 [ 1.73205081  2.        ]]

Exponent
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]]

Covariance
 [[ 0.5  0.5]
 [ 0.5  0.5]]

Maximumm
 4

Median
 2.5

Transpose
 [[1 3]
 [2 4]]


# Indexing and Slicing 

In [136]:
a = np.arange(5)
print(a)
print(a[3])
print(a[2:4])
print(a[:3])  # start from first element upto 3rd position(exclusive)
print(a[2:])  # start from 2nd position upto last element

[0 1 2 3 4]
3
[2 3]
[0 1 2]
[2 3 4]


Multi-dimensional array

In [151]:
a = np.arange(20).reshape(5, 4)
print('\nA\n', a)
print('\nFourth row\n',a[3])
print('\nA[1][2]\n', a[1][2])
print('\nA[1:4, :] From 2nd row till 4th row, includng all column\n', a[1:4, :])
print('\nA[:, 2:4] All row but 3rd and 4th column values\n', a[:, 2:4])


A
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Fourth row
 [12 13 14 15]

A[1][2]
 6

A[1:4, :] From 2nd row till 4th row, includng all column
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

A[:, 2:4] All row but 3rd and 4th column values
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


# Changing the shape of array

In [156]:
a = np.floor(np.random.random((2,4)) * 10)
a

array([[ 4.,  0.,  7.,  8.],
       [ 1.,  2.,  0.,  5.]])

In [158]:
np.ravel(a)    # Flatten the ndarry in 1d array

array([ 4.,  0.,  7.,  8.,  1.,  2.,  0.,  5.])

In [160]:
a.shape = (4,2)
a

array([[ 4.,  0.],
       [ 7.,  8.],
       [ 1.,  2.],
       [ 0.,  5.]])

In [162]:
a.transpose()

array([[ 4.,  7.,  1.,  0.],
       [ 0.,  8.,  2.,  5.]])

In [166]:
b = np.ceil(np.random.random((4, 2))*10)
b

array([[ 10.,   2.],
       [  2.,   4.],
       [  2.,   5.],
       [  1.,   2.]])

Stacking the arrays either vertically or horizontally

In [174]:
print(a)
print(b)
print('\nHorizontal Stack\n',np.hstack((a,b)))
print('\nVertical Stack\n',np.vstack((a,b)))

[[ 4.  0.]
 [ 7.  8.]
 [ 1.  2.]
 [ 0.  5.]]
[[ 10.   2.]
 [  2.   4.]
 [  2.   5.]
 [  1.   2.]]

Horizontal Stack
 [[  4.   0.  10.   2.]
 [  7.   8.   2.   4.]
 [  1.   2.   2.   5.]
 [  0.   5.   1.   2.]]

Vertical Stack
 [[  4.   0.]
 [  7.   8.]
 [  1.   2.]
 [  0.   5.]
 [ 10.   2.]
 [  2.   4.]
 [  2.   5.]
 [  1.   2.]]


In [175]:
np.r_[1:4,5,7]

array([1, 2, 3, 5, 7])

split the array in equal parts note the number of split should be of equal division.

In [180]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
np.hsplit(a, 4)

[array([[0],
        [4],
        [8]]), array([[1],
        [5],
        [9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [192]:
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# Indexing with array of indices

In [194]:
pallete = np.array([
                   [0,0,0],        # black
                   [255,0,0],       # red
                   [0,255,0],       # green
                   [0,0,255],       # blue
                   [255,255,255]    #white
                   ])    
image = np.array([[0,1,2,0], [0,3,4,0]])
pallete[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

Use of indexing with time series data

In [213]:
time = np.linspace(1,3,5)
data = np.sin(np.arange(20).reshape(4,5))
print('\nTime\n', time)
print('\nData\n',data)
# index of maximum value for each series
ind = data.argmax(axis=0)
time_max = time[ind]
print('\nTime at which value are maximumm are\n', time_max)
data_max = data[ind, np.arange(data.shape[1])]
print('\nData maximum\n', data_max)


Time
 [ 1.   1.5  2.   2.5  3. ]

Data
 [[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]]

Time at which value are maximumm are
 [ 2.5  1.   1.   1.5  2. ]

Data maximum
 [ 0.65028784  0.84147098  0.90929743  0.98935825  0.99060736]


# Indexing with boolean arrays

In [220]:
a = np.arange(12).reshape(3,4)
b = np.array([True, False, True])
c = np.array([True, False, True, False])

In [223]:
print('A\n', a)
print('\nA[b,:]\n',a[b,:])
print('\nA[c,:]\n',a[:,c])

A
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

A[b,:]
 [[ 0  1  2  3]
 [ 8  9 10 11]]

A[c,:]
 [[ 0  2]
 [ 4  6]
 [ 8 10]]


# Linear Algebra

In [225]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Transpose

In [228]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Identity matrix

In [230]:
I = np.eye(3)
I

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Trace of a matrix

In [231]:
np.trace(a)

15

Dot product

In [234]:
np.dot(a, I)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [240]:
A = np.matrix('1 2; 3 4')
print('A\n', A)
print('\nTranspose of A\n',A.T)

A
 [[1 2]
 [3 4]]

Transpose of A
 [[1 3]
 [2 4]]


In [241]:
X = np.matrix('2; 4')
X

matrix([[2],
        [4]])

In [253]:
print('A\n', A)
print('\nX\n', X)
print('\nA * X\n', A*X)

A
 [[1 2]
 [3 4]]

X
 [[2]
 [4]]

A * X
 [[10]
 [22]]


Inverse

In [249]:
A.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])